name: Continuous integration

on: [pull_request, push]

jobs:
  test:
    runs-on: windows-latest
    steps:
    # The Windows runners have autocrlf enabled by default
    # which causes failures for some of rustfmt's line-ending sensitive tests
    - name: disable git eol translation
      run: git config --global core.autocrlf false
    - name: checkout
      uses: actions/checkout@v3
    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: Win32
    - name: Stable with rustfmt and clippy
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        target: i686-pc-windows-msvc
        components: rustfmt, clippy
    - name: Lint code format
      run: cargo fmt --all -- --check
    - name: Lint code
      run: cargo clippy --all -- -D warnings
    - name: Test
      run: cargo test

